version: 0.2

env:
  variables:
    STACK_NAME: MyCodePipelineStack
    TEMPLATE_FILE: template.yml

phases:
  install:
    commands:
      - echo "Using built-in AWS CLI v2"

  pre_build:
    commands:
      - echo "Pre-build phase"
      - ls -la

  build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - |
        aws cloudformation deploy \
          --template-file $TEMPLATE_FILE \
          --stack-name $STACK_NAME \
          --capabilities CAPABILITY_NAMED_IAM \
          --debug

  post_build:
    commands:
      - echo "Deployment complete!"
      - |
        aws cloudformation describe-stacks \
          --stack-name $STACK_NAME \
          --query "Stacks[0].StackStatus" \
          --output text

artifacts:
  files:
    - '**/*'
