version: 0.2
env:
  variables:
    STACK_NAME: MyCodePipelineStack
    TEMPLATE_FILE: template.yml
phases:
  install:
    commands:
      - echo "Using built-in AWS CLI v2"
      - aws --version
  pre_build:
    commands:
      - echo "Pre-build phase"
      - ls -la
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --template-body file://$TEMPLATE_FILE
      - |
        echo "Checking stack status..."
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "DOES_NOT_EXIST")
        echo "Current stack status: $STACK_STATUS"
        
        if [ "$STACK_STATUS" != "DOES_NOT_EXIST" ]; then
          echo "Stack exists. Deleting to ensure clean deployment..."
          aws cloudformation delete-stack --stack-name $STACK_NAME
          echo "Waiting for stack deletion to complete..."
          aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME
          echo "Stack deleted successfully"
        fi
  build:
    commands:
      - echo "Creating CloudFormation stack using create-stack..."
      - |
        aws cloudformation create-stack \
          --stack-name $STACK_NAME \
          --template-body file://$TEMPLATE_FILE \
          --capabilities CAPABILITY_NAMED_IAM \
          --on-failure DELETE
      - echo "Waiting for stack creation to complete..."
      - aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
      - echo "Stack created successfully"
  post_build:
    commands:
      - echo "Deployment complete!"
      - |
        FINAL_STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "UNKNOWN")
        echo "Final stack status: $FINAL_STATUS"
        
        case "$FINAL_STATUS" in
          CREATE_COMPLETE|UPDATE_COMPLETE)
            echo "✓ Stack deployment successful"
            exit 0
            ;;
          *)
            echo "✗ Stack deployment failed with status: $FINAL_STATUS"
            exit 1
            ;;
        esac
artifacts:
  files:
    - '**/*'
