version: 0.2
env:
  variables:
    STACK_NAME: MyCodePipelineStack
    TEMPLATE_FILE: template.yml
phases:
  install:
    commands:
      - echo "Using built-in AWS CLI v2"
      - aws --version
  pre_build:
    commands:
      - echo "Pre-build phase"
      - ls -la
      - echo "Listing files in repository..."
  build:
    commands:
      - echo "Build phase - running application build/tests"
      - echo "✓ Build completed successfully"
      - |
        echo "NOTE: Infrastructure stack deployment should be done manually to avoid circular dependencies"
        echo "Current infrastructure stack status:"
        aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].{Name:StackName,Status:StackStatus}" --output table 2>/dev/null || echo "Stack not found"
  post_build:
    commands:
      - echo "Post-build phase"
      - echo "✓ Pipeline execution completed successfully"
artifacts:
  files:
    - '**/*'
